name: Continuous Deployment (No Docker)
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Get JAR file name
        id: jar-file
        run: |
          JAR_FILE=$(ls target/*.jar | grep -v original)
          echo "jar_path=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "jar_name=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ${{ steps.jar-file.outputs.jar_path }}
          target: /home/${{ secrets.EC2_USERNAME }}/app
          strip_components: 1

      - name: Start Application on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to app directory
            cd /home/${{ secrets.EC2_USERNAME }}/app
            
            # Stop existing application
            if [ -f app.pid ]; then
              PID=$(cat app.pid)
              if ps -p $PID > /dev/null 2>&1; then
                echo "Stopping existing application (PID: $PID)"
                kill -15 $PID
                sleep 5
                # Force kill if still running
                if ps -p $PID > /dev/null 2>&1; then
                  kill -9 $PID
                fi
              fi
              rm -f app.pid
            fi
            
            # Start new application
            nohup java -jar ${{ steps.jar-file.outputs.jar_name }} > application.log 2>&1 &
            echo $! > app.pid
            echo "Application started with PID: $(cat app.pid)"
            
            # Wait and verify
            sleep 5
            if ps -p $(cat app.pid) > /dev/null 2>&1; then
              echo "Application is running successfully"
            else
              echo "Failed to start application"
              exit 1
            fi